# -*- coding: utf-8 -*-
"""Class5_своя_VGG19TL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQ7F0v9hfTo9WiwZlPJn2HJMyqKiOFzD

Подготовка данных. Импорт zip архива.
"""

import os
import zipfile
import requests

def unzip_to_colab(zip_file_path, extract_path=None, delete_zip=False):

    try:
        # 1. Проверка файла
        if not os.path.exists(zip_file_path):
            print(f"Error: File '{zip_file_path}' not found.")
            return

        # 2. Путь
        if extract_path is None:
            extract_path = os.getcwd()  # Текущая директория
        else:
            # Создать директорию, если ее нет
            os.makedirs(extract_path, exist_ok=True)


        # 3. Распаковка
        with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
            zip_ref.extractall(extract_path)

        print(f"Zip archive '{zip_file_path}' successfully extracted to '{extract_path}'.")

        # 4. Delete the zip file (if specified)
        if delete_zip:
            try:
                os.remove(zip_file_path)
                print(f"Zip file '{zip_file_path}' deleted.")
            except OSError as e:
                print(f"Error deleting zip file: {e}")


    except zipfile.BadZipFile as e:
        print(f"Error: File '{zip_file_path}' is not a valid zip archive. Error: {e}")
    except FileNotFoundError as e:
        print(f"Error: File '{zip_file_path}' not found. Error: {e}")
    except Exception as e:
        print(f"An error occurred during extraction: {e}")


def download_and_save(url, save_path):
    """
    Загрузка файла с URL и сохранение его.
    """
    try:
        response = requests.get(url, stream=True)
        response.raise_for_status()

        with open(save_path, 'wb') as file:
            for chunk in response.iter_content(chunk_size=8192):
                file.write(chunk)
        print(f"File successfully downloaded and saved to: {save_path}")

    except requests.exceptions.RequestException as e:
        print(f"Error downloading file from '{url}': {e}")
        return False  # Indicate failure
    except Exception as e:
        print(f"An error occurred while downloading and saving the file: {e}")
        return False  # Indicate failure
    return True # Indicate success

zip_file_path = '/content/sample_data/dataset.zip'
extract_path = '/content/sample_data'
unzip_to_colab(zip_file_path, extract_path)

"""Разбивка данных на тренировочные и тестовые"""

import os
import random
import shutil

# 1. Определите пути и параметры
DATA_DIR = '/content/sample_data'  # Каталог с папками классов
TRAIN_DIR = '/content/train'      # Каталог для тренировочной выборки
TEST_DIR = '/content/test'        # Каталог для тестовой выборки
SPLIT_RATIO = 0.8                 # Соотношение тренировочной и тестовой выборки
RANDOM_SEED = 42                   # Для воспроизводимости результатов

# 2. Создание целевых каталогов
os.makedirs(TRAIN_DIR, exist_ok=True)
os.makedirs(TEST_DIR, exist_ok=True)

# 3. Для воспроизводимости
random.seed(RANDOM_SEED)

# 4. Получите список классов (подпапок в DATA_DIR)
classes = [d for d in os.listdir(DATA_DIR) if os.path.isdir(os.path.join(DATA_DIR, d))]
print(f"Обнаружены классы: {classes}")

# 5. Разделите данные для каждого класса
for class_name in classes:
    class_dir = os.path.join(DATA_DIR, class_name)
    images = os.listdir(class_dir)
    num_images = len(images)
    num_train = int(num_images * SPLIT_RATIO)

    # Перемешайте список файлов
    random.shuffle(images)

    # Разделите на тренировочную и тестовую выборки
    train_images = images[:num_train]
    test_images = images[num_train:]

    # 6. Создайте папки классов в тренировочном и тестовом каталогах
    train_class_dir = os.path.join(TRAIN_DIR, class_name)
    test_class_dir = os.path.join(TEST_DIR, class_name)
    os.makedirs(train_class_dir, exist_ok=True)
    os.makedirs(test_class_dir, exist_ok=True)

    # 7. Переместите файлы в соответствующие папки
    for image in train_images:
        src_path = os.path.join(class_dir, image)
        dst_path = os.path.join(train_class_dir, image)
        shutil.copyfile(src_path, dst_path)  # copyfile, чтобы не удалять файлы из исходной папки
        #os.rename(src_path, dst_path) #Если нужно переместить а не копировать файлы раскомментируйте эту строку и закоментируйте shutil.copyfile

    for image in test_images:
        src_path = os.path.join(class_dir, image)
        dst_path = os.path.join(test_class_dir, image)
        shutil.copyfile(src_path, dst_path)  # Используйте copyfile, чтобы не удалять файлы из исходной папки
        #os.rename(src_path, dst_path) #Если нужно переместить а не копировать файлы раскомментируйте эту строку и закоментируйте shutil.copyfile
    # 8. Выведите статистику
    print(f"Класс: {class_name}")
    print(f"  Всего изображений: {num_images}")
    print(f"  Тренировочных изображений: {len(train_images)}")
    print(f"  Тестовых изображений: {len(test_images)}")

print("Разделение данных завершено.")

"""Вывод информации об образце из DataGeneration

"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
image_path = '/content/train/attrition/def11.jpg'

img = mpimg.imread(image_path)

plt.imshow(img)
plt.axis('off')
plt.show()

import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator
img_width, img_height = 224, 224  # Размер изображений
batch_size = 16   # Размер батча
train_dir = '/content/train'  # Путь к тренировочным данным
val_dir = '/content/test'  # Путь к валидационным данным
#Создайте экземпляры двух классов генераторов изображений:
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=30,        # случайные повороты на +-30 градусов
    horizontal_flip=True,     # случайное отражение по горизонтали
    fill_mode='reflect',       # заполнение пустых мест отражением краёв
    validation_split=0.2
)

valid_datagen = ImageDataGenerator(
    rescale=1.0/255,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    directory=train_dir,
    target_size=(224, 224),
    classes=['attrition', 'label', 'nodefects', 'pores', 'scratch'],
    color_mode = 'grayscale',
    class_mode='categorical',
    batch_size=batch_size,
    shuffle=True,
    seed=42,
    )

valid_generator = valid_datagen.flow_from_directory(
    directory=val_dir,
    target_size=(224, 224),
    classes=['attrition', 'label', 'nodefects', 'pores', 'scratch'],
    color_mode = 'grayscale',
    class_mode='categorical',
    batch_size=batch_size,
    )
# Проверяем форму первого пакета
x_batch, y_batch = next(train_generator)
print("Shape of x_batch:", x_batch.shape)  # Должно быть (batch_size, 224, 224, num_channels)
x_batch, y_batch = next(valid_generator)
print("Shape of x_batch:", x_batch.shape)

data_batch, labels_batch = train_generator.__next__()
# Проверка классов
print("Классы:", train_generator.class_indices)
# Вывод информации о пакете
print("Размер пакета изображений (data_batch.shape):", data_batch.shape)  # (batch_size, img_width, img_height, channels)
print("Размер пакета меток (labels_batch.shape):", labels_batch.shape)  # (batch_size,)  (или (batch_size, num_classes) для categorical)
print("Тип данных изображений (data_batch.dtype):", data_batch.dtype)
print("Тип данных меток (labels_batch.dtype):", labels_batch.dtype)
print("Метки в пакете (labels_batch):", labels_batch)  # Вывод меток

# Вывод информации о генераторе
print("\nАтрибуты train_generator:")
print("  .directory:", train_generator.directory)  # Корневой каталог
print("  .image_shape:", train_generator.image_shape)  # Размеры изображения (высота, ширина, каналы)
print("  .num_classes:", train_generator.num_classes)  # Количество классов
print("  .class_indices:", train_generator.class_indices)  # Словарь сопоставления имен классов с индексами
print("  .samples:", train_generator.samples)  # Общее количество образцов
print("  .batch_size:", train_generator.batch_size)  # Размер пакета
print("  .target_size:", train_generator.target_size)  # Целевой размер изображения
print("  .color_mode:", train_generator.color_mode)  # Цветовой режим
print("  .class_mode:", train_generator.class_mode)  # Режим классов
print("  .shuffle:", train_generator.shuffle)  # Перемешивание

import tensorflow as tf
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input
# Создание модели классификации
model = Sequential(),
inputs = Input(shape=(224, 224, 1))
x = Conv2D(32, 3, activation="relu", padding="same")(inputs)
x = MaxPooling2D(pool_size=2)(x)
x = Conv2D(64, 3, activation="relu", padding="same")(x)
#x = MaxPooling2D(pool_size=2)(x)
x = Flatten()(x)
x = Dense(64, activation="relu")(x)

    # Выход: [x, y, width, height, class_id]
output = Dense(5, activation="softmax")(x)
model = tf.keras.Model(inputs, output)
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
model.summary()

from keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint('best_model.h5', monitor='val_loss', save_best_only=True)
history = model.fit(train_generator, epochs=10, batch_size=8, validation_data=valid_generator, callbacks=[checkpoint])

# history = model.fit(
#     train_generator,
#     steps_per_epoch=train_generator.samples // batch_size,
#     epochs=epochs,
#     validation_data=valid_generator,
#     validation_steps=valid_generator.samples // batch_size)
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(1, len(acc) + 1)

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend()
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend()
plt.title('Training and Validation Loss')

plt.show()

# Оценка модели на тестовых данных
valid_generator = valid_datagen.flow_from_directory(
    directory=val_dir,
    target_size=(224, 224),
    classes=['attrition', 'label', 'nodefects', 'pores', 'scratch'],
    color_mode = 'grayscale',
    class_mode='categorical',
    batch_size=batch_size,
    shuffle=False  # Важно для правильного вычисления метрик
)

print(len(valid_generator.classes))
print(valid_generator.class_indices)

print(np.unique(classes))

import numpy as np
from sklearn.metrics import accuracy_score

# 1. Получение предсказаний от модели
predictions = model.predict(valid_generator)

# 2. Получение истинных меток (ground truth) из val_generator

true_classes = valid_generator.classes  # Если это DirectoryIterator

# 3. Преобразование вероятностей в классы (если модель предсказывает вероятности)

predicted_classes = np.argmax(predictions, axis=1)

# 4. Вычисление accuracy
accuracy = accuracy_score(true_classes, predicted_classes)

# 5. Вывод метрики
print(f"Accuracy: {accuracy}")

from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Вариант 1: Расчет метрик для каждого класса отдельно (average=None)
precision = precision_score(true_classes, predicted_classes, average=None)
recall = recall_score(true_classes, predicted_classes, average=None)
f1 = f1_score(true_classes, predicted_classes, average=None)

print("Precision per class:", precision)
print("Recall per class:", recall)
print("F1-score per class:", f1)

# Общие метрики и отчет о классификации (рекомендуется использовать classification_report)
conf_matrix = confusion_matrix(true_classes, predicted_classes)  # Матрица ошибок
class_report = classification_report(true_classes, predicted_classes) # Отчет о классификации

print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

true_classes = valid_generator.classes

print("Class Indices:", valid_generator.class_indices)

classes = ['attrition', 'label', 'nodefects', 'pores', 'scratch']

import seaborn as sns
def plot_confusion_matrix(true_classes, predicted_classes, classes, title='Confusion Matrix', cmap='Blues'):  # classes теперь обязательный аргумент
    cm = confusion_matrix(true_classes, predicted_classes)

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap=cmap, xticklabels=classes, yticklabels=classes)
    plt.title(title)
    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# 6. Вывод метрик
accuracy = accuracy_score(true_classes, predicted_classes)
print(f"Accuracy: {accuracy}")

precision = precision_score(true_classes, predicted_classes, average=None)
recall = recall_score(true_classes, predicted_classes, average=None)
f1 = f1_score(true_classes, predicted_classes, average=None)

print("Precision per class:", precision)
print("Recall per class:", recall)
print("F1-score per class:", f1)

conf_matrix = confusion_matrix(true_classes, predicted_classes)
class_report = classification_report(true_classes, predicted_classes, target_names=classes) # Указываем target_names

print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

# 7. Вывод матрицы соответствия (ОБЯЗАТЕЛЬНО передаем список classes)
plot_confusion_matrix(true_classes, predicted_classes, classes=classes, title='Confusion Matrix', cmap='Blues')

"""Увеличиваемт количество изображений в обучающем наборе за счёт аугментации.
Нормализуем пиксели: преобразуем значения в диапазон [0,1].
Создаём генераторы данных: train_generator и val_generator.
"""

import os
from tensorflow.keras.applications import VGG19
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.regularizers import l2
from PIL import Image
import matplotlib.pyplot as plt
from keras.optimizers import Adam

!pip install opencv-python tqdm

"""Код пройдет по всем изображениям в grayscale, преобразует их в RGB и сохранит в соответствующие папки в указанных выходных директориях. tqdm будет показывать прогресс преобразования.
1. Импортирует необходимые библиотеки:
  - os: Для работы с файловой системой (создание папок, перечисление файлов).
  - cv2: OpenCV (cv2) для чтения и записи изображений, а также для преобразования цветовых пространств.
  - numpy: Для работы с массивами (изображения представляются как массивы).
  - tqdm: Для отображения прогресс-бара.
2. Функция grayscale_to_rgb(input_dir, output_dir):
  - Принимает пути к входной и выходной папкам.
  - Проверяет существование входной папки.
  - Создает выходную папку (и подпапки классов), если она не существует.
  - Перебирает подпапки (классы) во входной папке.
  - Перебирает файлы изображений в каждой папке класса.
  - Для каждого изображения:
   - Читает изображение в grayscale с помощью cv2.imread(image_path, cv2.IMREAD_GRAYSCALE).
   - Преобразует grayscale изображение в RGB с помощью cv2.cvtColor(img_gray, cv2.COLOR_GRAY2RGB).
   - Сохраняет RGB изображение с помощью cv2.imwrite(output_path, img_rgb).
  - Обрабатывает исключения (ошибки при чтении или записи изображений).

"""

import os

def create_directory(directory_path):
    """Создает директорию, если она еще не существует.

    Args:
        directory_path (str): Путь к директории, которую нужно создать.
    """
    if not os.path.exists(directory_path):
        try:
            os.makedirs(directory_path)
            print(f"Директория '{directory_path}' успешно создана.")
        except OSError as e:
            print(f"Ошибка при создании директории '{directory_path}': {e}")
    else:
        print(f"Директория '{directory_path}' уже существует.")

# Определяем пути для папок
train_grayscale_path = "train_rgb_images"
test_rgb_path = "test_rgb_images"

# Создаем папки
create_directory(train_grayscale_path)
create_directory(test_rgb_path)

print("Готово.")

import os
import cv2
import numpy as np
from tqdm import tqdm  # Для отображения прогресса

def grayscale_to_rgb(input_dir, output_dir):
    """
    Преобразует изображения в grayscale в RGB формат, сохраняя структуру папок.
    Args:
        input_dir (str): Путь к папке с изображениями в grayscale, рассортированными по классам.
                         Структура должна быть: input_dir/класс1/изображения, input_dir/класс2/изображения, ...
        output_dir (str): Путь к папке, где будут сохранены преобразованные изображения в RGB.
                          Будет создана аналогичная структура папок.
    """

    # Проверяем, существует ли входная папка
    if not os.path.exists(input_dir):
        print(f"Ошибка: Входная папка '{input_dir}' не существует.")
        return

    # Создаем выходную папку, если она не существует
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Получаем список классов (подпапок) во входной папке
    classes = os.listdir(input_dir)
    print(f"Найдены классы: {classes}")

    for class_name in classes:
        class_input_dir = os.path.join(input_dir, class_name)
        class_output_dir = os.path.join(output_dir, class_name)

        # Проверяем, что это действительно папка
        if not os.path.isdir(class_input_dir):
            print(f"Предупреждение: '{class_input_dir}' не является папкой. Пропускаем.")
            continue

        # Создаем папку класса в выходной папке
        if not os.path.exists(class_output_dir):
            os.makedirs(class_output_dir)

        # Получаем список файлов изображений в папке класса
        image_files = os.listdir(class_input_dir)

        print(f"Обработка класса: {class_name}")
        for image_file in tqdm(image_files, desc=f"Преобразование изображений в {class_name}"):
            image_path = os.path.join(class_input_dir, image_file)
            output_path = os.path.join(class_output_dir, image_file)

            try:
                # Читаем изображение в grayscale
                img_gray = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

                # Проверяем, успешно ли прочитано изображение
                if img_gray is None:
                    print(f"Ошибка: Не удалось прочитать изображение '{image_path}'. Пропускаем.")
                    continue

                # Преобразуем в RGB
                img_rgb = cv2.cvtColor(img_gray, cv2.COLOR_GRAY2RGB)

                # Сохраняем изображение в RGB
                cv2.imwrite(output_path, img_rgb)

            except Exception as e:
                print(f"Ошибка при обработке изображения '{image_path}': {e}. Пропускаем.")

# Запуск преобразования
train_input_dir = "/content/train"  # Замените на путь к вашей папке train
train_output_dir = "/content/train_rgb_images"  # Замените на путь, куда сохранить train RGB
test_input_dir = "/content/test"  # Замените на путь к вашей папке test
test_output_dir = "/content/test_rgb_images"  # Замените на путь, куда сохранить test RGB

grayscale_to_rgb(train_input_dir, train_output_dir)
grayscale_to_rgb(test_input_dir, test_output_dir)

print("Преобразование завершено.")

"""
Загрузка обученной модели."""

img_width, img_height = 224, 224  # Размер изображений
batch_size = 16   # Размер батча
train_dir = '/content/train_rgb_images'  # Путь к тренировочным данным
val_dir = '/content/test_rgb_images'  # Путь к валидационным данным
#Создайте экземпляры двух классов генераторов изображений:
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,     # случайное отражение по горизонтали
    fill_mode='reflect',       # заполнение пустых мест отражением краёв
    validation_split=0.2
)

valid_datagen = ImageDataGenerator(
    rescale=1.0/255,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    directory=train_dir,
    target_size=(224, 224),
    classes=['attrition', 'label', 'nodefects', 'pores', 'scratch'],
    color_mode = 'rgb',
    class_mode='categorical',
    batch_size=batch_size,
    shuffle=True,
    seed=42,
    )

valid_generator = valid_datagen.flow_from_directory(
    directory=val_dir,
    target_size=(224, 224),
    classes=['attrition', 'label', 'nodefects', 'pores', 'scratch'],
    color_mode = 'rgb',
    class_mode='categorical',
    batch_size=batch_size,
    )
# Проверяем форму первого пакета
x_batch, y_batch = next(train_generator)
print("Shape of x_batch:", x_batch.shape)  # Должно быть (batch_size, 224, 224, num_channels)
x_batch, y_batch = next(valid_generator)
print("Shape of x_batch:", x_batch.shape)

# # Загрузка модели
# import keras
# from tensorflow.keras.applications import VGG19
# from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
# from tensorflow.keras.models import Model
from tensorflow.keras.initializers import HeNormal
base_model = VGG19 (include_top=False, weights='imagenet', input_shape=(224, 224, 3))

base_model.summary()

for layer in base_model.layers:
    layer.trainable = False
# Добавление своих классифицирующих слоев (поверх VGG19)

# flattened превращает выходы сверточных слоев в одномерный вектор как в прошлой работе

# Преобразуем двумерные данные в вектор
keras.layers.Flatten(),

# Instantiate the sequential model and add the model:
model = Sequential()
model.add(base_model)

# Add the custom layers atop the model:
model.add(Flatten(name='flattened'))
model.add(Dropout(0.5))
model.add(Dense(64,
                activation='relu',
                kernel_initializer=HeNormal()))
model.add(Dropout(0.7))
model.add(Dense(5, activation='softmax', kernel_regularizer=l2(0.02), name='predictions'))
model.compile(optimizer=Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# # import tensorflow as tf
# # from tensorflow.keras.preprocessing.image import ImageDataGenerator
# # from tensorflow.keras.applications import VGG19
# from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Flatten, Dropout
# # from tensorflow.keras.models import Model, Sequential
# # from tensorflow.keras.optimizers import Adam
# from tensorflow.keras.regularizers import l2
# from sklearn.metrics import accuracy_score
# import numpy as np

# img_width, img_height = 224, 224
# batch_size = 16
# epochs = 20
# train_dir = '/content/test_rgb_images' # Замените
# val_dir = '/content/test_rgb_images'     # Замените
# num_classes = 5 # Замените

# base_model = VGG19(weights='imagenet', include_top=False, input_shape=(img_width, img_height, 3))
# base_model.trainable = False # Замораживаем веса базовой модели

# model = Sequential()
# model.add(base_model)
# model.add(Flatten(name='flattened'))
# model.add(Dropout(0.5))
# model.add(Dense(64, activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(32, activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(num_classes, activation='softmax', kernel_regularizer=l2(0.01), name='predictions'))

# model.compile(optimizer=Adam(learning_rate=0.0001),
#               loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

# Проверка количества данных и batch_size
print("Number of training samples:", train_generator.samples)
print("Number of validation samples:", valid_generator.samples)
print("Batch size:", batch_size)

# Проверка наличия классов
print("Training class indices:", train_generator.class_indices)
print("Validation class indices:", valid_generator.class_indices)

# Вычисление steps_per_epoch и validation_steps (округление вверх)
steps_per_epoch = max(1, train_generator.samples // batch_size) # Убедитесь, что steps_per_epoch > 0
validation_steps = max(1, valid_generator.samples // batch_size) # Убедитесь, что validation_steps > 0

checkpoint = ModelCheckpoint('best_model_VG.h5', monitor='val_loss', save_best_only=True)
history = model.fit(train_generator, epochs=20, batch_size=16, validation_data=valid_generator, callbacks=[checkpoint])

history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // batch_size,
    epochs=epochs,
    validation_data=valid_generator,
    validation_steps=valid_generator.samples // batch_size)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(1, len(acc) + 1)

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend()
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend()
plt.title('Training and Validation Loss')

plt.show()

# Evaluation
# No need to redefine valid_generator here, reuse the one defined earlier
valid_generator = valid_datagen.flow_from_directory(
    directory=val_dir,
    target_size=(224, 224),
    classes=['attr', 'label', 'no', 'pores', 'scr'],
    class_mode='categorical',
    batch_size=batch_size,
    shuffle = False,
    )
predictions = model.predict(valid_generator)
predicted_classes = np.argmax(predictions, axis=1)

true_classes = valid_generator.classes
class_labels = list(valid_generator.class_indices.keys())

print(f"Accuracy: {accuracy_score(true_classes, predicted_classes)}")

import tensorflow as tf

# Сохранение всей модели (архитектура, веса, конфигурация обучения, оптимизатор)
model.save('my_model.h5')

# Загрузка модели
loaded_model = tf.keras.models.load_model('my_model.h5')

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(1, len(acc) + 1)

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend()
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend()
plt.title('Training and Validation Loss')

plt.show()



from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Вариант 1: Расчет метрик для каждого класса отдельно (average=None)
precision = precision_score(true_classes, predicted_classes, average=None)
recall = recall_score(true_classes, predicted_classes, average=None)
f1 = f1_score(true_classes, predicted_classes, average=None)

print("Precision per class:", precision)
print("Recall per class:", recall)
print("F1-score per class:", f1)

# Общие метрики и отчет о классификации (рекомендуется использовать classification_report)
conf_matrix = confusion_matrix(true_classes, predicted_classes)  # Матрица ошибок
class_report = classification_report(true_classes, predicted_classes) # Отчет о классификации

print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

# Вариант 2: Использование 'micro' усреднения (подходит, когда важен общий результат)
precision_micro = precision_score(true_classes, predicted_classes, average='micro')
recall_micro = recall_score(true_classes, predicted_classes, average='micro')
f1_micro = f1_score(true_classes, predicted_classes, average='micro')

print("Micro-averaged precision:", precision_micro)
print("Micro-averaged recall:", recall_micro)
print("Micro-averaged F1-score:", f1_micro)

# Вариант 3: Использование 'macro' усреднения (подходит, когда все классы одинаково важны)
precision_macro = precision_score(true_classes, predicted_classes, average='macro')
recall_macro = recall_score(true_classes, predicted_classes, average='macro')
f1_macro = f1_score(true_classes, predicted_classes, average='macro')

print("Macro-averaged precision:", precision_macro)
print("Macro-averaged recall:", recall_macro)
print("Macro-averaged F1-score:", f1_macro)

# Вариант 4: Использование 'weighted' усреднения (учитывает количество экземпляров в каждом классе)
precision_weighted = precision_score(true_classes, predicted_classes, average='weighted')
recall_weighted = recall_score(true_classes, predicted_classes, average='weighted')
f1_weighted = f1_score(true_classes, predicted_classes, average='weighted')

print("Weighted-averaged precision:", precision_weighted)
print("Weighted-averaged recall:", recall_weighted)
print("Weighted-averaged F1-score:", f1_weighted)

predictions = model.predict(valid_generator)
predicted_classes = np.argmax(predictions, axis=1)

true_classes = valid_generator.classes
class_labels = list(valid_generator.class_indices.keys())
print(f"Accuracy: {accuracy_score(true_classes, predicted_classes)}")
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)